upstream frontend {
    server frontend:3000;
}

upstream backend {
    server backend:5002;
}

upstream admin {
    server admin:80;
}

server {
    listen 80;

    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
    }

    location /api/ {
        proxy_pass http://backend:5002/;
        proxy_set_header Host $host;
    }

    location /admin/ {
        proxy_pass http://admin:80/;
        proxy_set_header Host $host;
    }

    location = /admin {
        return 301 /admin/;
    }
}